// Static placeholder data for Contact Requests UI only.
// No API / service layer — replace with real data when backend is ready.

export const PIPELINE_STAGES = [
  "New",
  "Contacted",
  "Qualified",
  "Meeting Scheduled",
  "Proposal Sent",
  "Won",
  "Lost",
  "Closed",
];

export const PRIORITY_OPTIONS = ["High", "Medium", "Low"];
export const ASSIGNEE_OPTIONS = ["Unassigned", "Priya Nair", "Rohan Mehta", "Isha Verma", "Aarav Sharma"];
export const INDUSTRY_OPTIONS = ["Technology", "Finance", "Healthcare", "Retail", "Manufacturing", "Education"];
export const COUNTRY_OPTIONS = ["India", "United States", "United Kingdom", "UAE", "Singapore"];

export const PLACEHOLDER_REQUESTS = [
  {
    id: 1,
    name: "Rajesh Kumar",
    company: "TechNova Solutions",
    email: "rajesh@technova.com",
    phone: "+91 98765 43210",
    country: "India",
    industry: "Technology",
    message: "We are looking for an AI-powered customer support solution for our enterprise clients.",
    stage: "New",
    priority: "High",
    status: "Open",
    assignedTo: "Unassigned",
    submittedAt: "2026-07-20T08:30:00Z",
    avatarColor: "#3A8D9D",
    activities: [
      { id: "a1", label: "Request Received", at: "2026-07-20T08:30:00Z" },
    ],
  },
  {
    id: 2,
    name: "Emily Watson",
    company: "FinEdge Corp",
    email: "emily.watson@finedge.com",
    phone: "+1 415 555 0192",
    country: "United States",
    industry: "Finance",
    message: "Interested in automation for loan processing workflows.",
    stage: "New",
    priority: "Medium",
    status: "Open",
    assignedTo: "Priya Nair",
    submittedAt: "2026-07-19T14:15:00Z",
    avatarColor: "#7c3aed",
    activities: [
      { id: "a1", label: "Request Received", at: "2026-07-19T14:15:00Z" },
    ],
  },
  {
    id: 3,
    name: "Mohammed Al-Rashid",
    company: "Gulf Retail Group",
    email: "m.alrashid@gulfretail.ae",
    phone: "+971 50 123 4567",
    country: "UAE",
    industry: "Retail",
    message: "Need a demo for our e-commerce personalization use case.",
    stage: "Contacted",
    priority: "High",
    status: "In Progress",
    assignedTo: "Rohan Mehta",
    submittedAt: "2026-07-18T10:00:00Z",
    avatarColor: "#ea580c",
    activities: [
      { id: "a1", label: "Request Received", at: "2026-07-18T10:00:00Z" },
      { id: "a2", label: "Assigned to Sales", at: "2026-07-18T11:30:00Z" },
    ],
  },
  {
    id: 4,
    name: "Sarah Chen",
    company: "MediCare Plus",
    email: "sarah.chen@medicareplus.com",
    phone: "+65 9123 4567",
    country: "Singapore",
    industry: "Healthcare",
    message: "Exploring AI for patient intake and triage automation.",
    stage: "Qualified",
    priority: "High",
    status: "In Progress",
    assignedTo: "Isha Verma",
    submittedAt: "2026-07-17T09:45:00Z",
    avatarColor: "#16a34a",
    activities: [
      { id: "a1", label: "Request Received", at: "2026-07-17T09:45:00Z" },
      { id: "a2", label: "Assigned to Sales", at: "2026-07-17T10:00:00Z" },
      { id: "a3", label: "Qualified Lead", at: "2026-07-18T15:00:00Z" },
    ],
  },
  {
    id: 5,
    name: "James Wilson",
    company: "BuildRight Manufacturing",
    email: "j.wilson@buildright.co.uk",
    phone: "+44 7700 900123",
    country: "United Kingdom",
    industry: "Manufacturing",
    message: "Looking for predictive maintenance AI solutions.",
    stage: "Meeting Scheduled",
    priority: "Medium",
    status: "In Progress",
    assignedTo: "Aarav Sharma",
    submittedAt: "2026-07-16T13:20:00Z",
    avatarColor: "#2563eb",
    activities: [
      { id: "a1", label: "Request Received", at: "2026-07-16T13:20:00Z" },
      { id: "a2", label: "Assigned to Sales", at: "2026-07-16T14:00:00Z" },
      { id: "a3", label: "Meeting Scheduled", at: "2026-07-19T10:00:00Z" },
    ],
  },
  {
    id: 6,
    name: "Anita Desai",
    company: "EduLearn Academy",
    email: "anita@edulearn.in",
    phone: "+91 99887 76655",
    country: "India",
    industry: "Education",
    message: "Want to discuss AI tutoring and content recommendation.",
    stage: "Proposal Sent",
    priority: "Medium",
    status: "In Progress",
    assignedTo: "Priya Nair",
    submittedAt: "2026-07-15T11:00:00Z",
    avatarColor: "#db2777",
    activities: [
      { id: "a1", label: "Request Received", at: "2026-07-15T11:00:00Z" },
      { id: "a2", label: "Proposal Sent", at: "2026-07-17T16:30:00Z" },
    ],
  },
  {
    id: 7,
    name: "David Park",
    company: "CloudSync Inc",
    email: "david@cloudsync.io",
    phone: "+1 212 555 0147",
    country: "United States",
    industry: "Technology",
    message: "Enterprise AI integration for our SaaS platform.",
    stage: "Won",
    priority: "High",
    status: "Closed",
    assignedTo: "Aarav Sharma",
    submittedAt: "2026-07-10T08:00:00Z",
    avatarColor: "#0d9488",
    activities: [
      { id: "a1", label: "Request Received", at: "2026-07-10T08:00:00Z" },
      { id: "a2", label: "Marked Won", at: "2026-07-14T17:00:00Z" },
    ],
  },
  {
    id: 8,
    name: "Lisa Thompson",
    company: "QuickShop Retail",
    email: "lisa@quickshop.com",
    phone: "+1 310 555 0188",
    country: "United States",
    industry: "Retail",
    message: "Budget constraints — may revisit next quarter.",
    stage: "Lost",
    priority: "Low",
    status: "Closed",
    assignedTo: "Rohan Mehta",
    submittedAt: "2026-07-08T15:30:00Z",
    avatarColor: "#64748b",
    activities: [
      { id: "a1", label: "Request Received", at: "2026-07-08T15:30:00Z" },
      { id: "a2", label: "Marked Lost", at: "2026-07-12T09:00:00Z" },
    ],
  },
  {
    id: 9,
    name: "Vikram Patel",
    company: "SecureBank Ltd",
    email: "vikram.p@securebank.in",
    phone: "+91 91234 56789",
    country: "India",
    industry: "Finance",
    message: "Completed engagement — no further action needed.",
    stage: "Closed",
    priority: "Low",
    status: "Closed",
    assignedTo: "Isha Verma",
    submittedAt: "2026-06-28T10:00:00Z",
    avatarColor: "#9333ea",
    activities: [
      { id: "a1", label: "Request Received", at: "2026-06-28T10:00:00Z" },
      { id: "a2", label: "Marked Won", at: "2026-07-05T12:00:00Z" },
      { id: "a3", label: "Closed", at: "2026-07-10T14:00:00Z" },
    ],
  },
  {
    id: 10,
    name: "Sophie Martin",
    company: "HealthFirst Clinics",
    email: "sophie.m@healthfirst.fr",
    phone: "+33 6 12 34 56 78",
    country: "United Kingdom",
    industry: "Healthcare",
    message: "Initial inquiry about conversational AI for appointments.",
    stage: "Contacted",
    priority: "Medium",
    status: "In Progress",
    assignedTo: "Priya Nair",
    submittedAt: "2026-07-19T07:20:00Z",
    avatarColor: "#e11d48",
    activities: [
      { id: "a1", label: "Request Received", at: "2026-07-19T07:20:00Z" },
      { id: "a2", label: "Assigned to Sales", at: "2026-07-19T09:00:00Z" },
    ],
  },
];

export const SUMMARY_STATS = {
  total: PLACEHOLDER_REQUESTS.length,
  new: PLACEHOLDER_REQUESTS.filter((r) => r.stage === "New").length,
  qualified: PLACEHOLDER_REQUESTS.filter((r) => r.stage === "Qualified").length,
  won: PLACEHOLDER_REQUESTS.filter((r) => r.stage === "Won").length,
  lost: PLACEHOLDER_REQUESTS.filter((r) => r.stage === "Lost").length,
  closed: PLACEHOLDER_REQUESTS.filter((r) => r.stage === "Closed").length,
};
